'use strict';

/**
 * @fileoverview Mongoose ChatLog model for persisting conversation analytics data.
 * Records each chatbot exchange with performance metrics and retrieved docs.
 */

const mongoose = require('mongoose');

/**
 * @typedef {Object} IChatLog
 * @property {string} sessionId - The session this message belongs to
 * @property {string} userMessage - The message sent by the user
 * @property {string} botResponse - The response generated by the bot
 * @property {number} tokensUsed - Number of LLM tokens consumed
 * @property {number} latencyMs - Time in ms from request to response
 * @property {string[]} retrievedDocs - Snippets of vector DB documents used
 * @property {string} intent - Detected intent label
 * @property {string} llmProvider - Which LLM was used ('openai'|'gemini')
 * @property {Date} timestamp - When this exchange occurred
 */

const chatLogSchema = new mongoose.Schema(
  {
    sessionId: {
      type: String,
      required: [true, 'Session ID is required'],
      index: true,
    },
    userMessage: {
      type: String,
      required: [true, 'User message is required'],
      maxlength: [5000, 'User message too long'],
    },
    botResponse: {
      type: String,
      required: [true, 'Bot response is required'],
      maxlength: [20000, 'Bot response too long'],
    },
    tokensUsed: {
      type: Number,
      default: 0,
      min: [0, 'Token count cannot be negative'],
    },
    latencyMs: {
      type: Number,
      default: 0,
      min: [0, 'Latency cannot be negative'],
    },
    retrievedDocs: {
      type: [String],
      default: [],
    },
    intent: {
      type: String,
      default: 'unknown',
      maxlength: [100, 'Intent label too long'],
    },
    llmProvider: {
      type: String,
      enum: ['openai', 'gemini', 'fallback'],
      default: 'openai',
    },
    feedback: {
      rating: { type: Number, min: 1, max: 5, default: null },
      comment: { type: String, maxlength: 500, default: '' },
    },
    timestamp: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  {
    timestamps: false, // Using custom timestamp field
    toJSON: {
      transform(doc, ret) {
        delete ret.__v;
        return ret;
      },
    },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
chatLogSchema.index({ sessionId: 1, timestamp: -1 });
chatLogSchema.index({ timestamp: -1 });
chatLogSchema.index({ intent: 1 });
chatLogSchema.index({ llmProvider: 1 });

// ─── Static Methods ───────────────────────────────────────────────────────────

/**
 * Returns aggregate analytics for the past N days.
 * @param {number} days - Number of days to look back
 * @returns {Promise<Object>} Analytics aggregate result
 */
chatLogSchema.statics.getDailyStats = async function getDailyStats(days = 7) {
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  return this.aggregate([
    { $match: { timestamp: { $gte: since } } },
    {
      $group: {
        _id: {
          year: { $year: '$timestamp' },
          month: { $month: '$timestamp' },
          day: { $dayOfMonth: '$timestamp' },
        },
        count: { $sum: 1 },
        avgLatency: { $avg: '$latencyMs' },
        totalTokens: { $sum: '$tokensUsed' },
      },
    },
    { $sort: { '_id.year': 1, '_id.month': 1, '_id.day': 1 } },
  ]);
};

/**
 * Returns the most frequent intents.
 * @param {number} limit - Max intents to return
 * @returns {Promise<Object[]>}
 */
chatLogSchema.statics.getTopIntents = async function getTopIntents(limit = 10) {
  return this.aggregate([
    { $group: { _id: '$intent', count: { $sum: 1 } } },
    { $sort: { count: -1 } },
    { $limit: limit },
    { $project: { intent: '$_id', count: 1, _id: 0 } },
  ]);
};

const ChatLog = mongoose.model('ChatLog', chatLogSchema);

module.exports = ChatLog;
